### PR TITLE
Add Dependabot, Update Dependencies

### PR DESCRIPTION
**Pull request by CanerKaraca23**
- Add Dependabot
- Add Update Gradle Wrapper Action
- Update Dependencies
- Update Gradle Wrapper

### CODE REVIEW

**Comment by transaero21** [comment]
Top 10 bad ideas: number 1 - let compose libs be updated automatically

**Comment by CanerKaraca23** [comment]
> Top 10 bad ideas: number 1 - let compose libs be updated automatically

Then remove dependabot only.

**Comment by polodarb** [comment]
Sorry, but updating all dependencies can cause serious problems. Required careful testing when updating libraries

**Comment by transaero21** [comment]
IMO there is still no point in any auto updating stuff, things like gradle are updated manually once a century, the new subrelease will not bring significant changes, but a new cache directory will be created for the new version of gradle, which will take up a few more gigabytes

**Comment by transaero21** [comment]
Plus, what's the point of notifying on github, when you can literally can see new releases from android studio

**Comment by CanerKaraca23** [comment]
Thanks for the answers but i still think keeping things up-to-date is always good. Especially like gradle wrapper or minor dependency updates, it will not harm you.

**Pull request closed without merging**
